convert MainModule.java to kotlin
rakshakhegde/DaggerAndroidInjector pull request #3
Opened 2017-10-26 22:08 UTC by loicsiret

Following some instruction on :
https://google.github.io/dagger/faq.html#What do I do instead?
Annotation @Module was missing on the conpanion object. Also as you
wish to have a static provides you need to add a @JVMStatic.

2017-10-26 22:10 UTC, digitalbuddha commented on app/src/main/java/me/rakshakhegde/dagger_android_injector/screens/main_screen/MainModule.kt
> +@@Module
double @ symbol

2017-10-27 18:55 UTC, loicsiret commented
Hmmm, It seems that I'm not authorized to see bitrise logs.
Can someone post the check failed stacktrace ?

2017-10-28 11:51 UTC, rakshakhegde commented
Bitrise logs:
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'src'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:3.0.0-rc2.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0-rc2/gradle-3.0.0-rc2.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0-rc2/gradle-3.0.0-rc2.jar
     Required by:
         project :
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 24s
exit status 1
```

2017-10-28 11:53 UTC, rakshakhegde requested changes

2017-10-28 11:53 UTC, rakshakhegde commented on build.gradle
> +		classpath 'com.android.tools.build:gradle:3.0.0-rc2'
Change it back to $compiler_version

2017-10-28 11:53 UTC, rakshakhegde commented on build.gradle
>  		compiler_version = "2.4.0-alpha7"
Modify this instead

2017-10-30 14:32 UTC, loicsiret commented on build.gradle
> +		classpath 'com.android.tools.build:gradle:3.0.0-rc2'
done

2017-10-31 08:09 UTC, rakshakhegde commented
@loicsiret Please check buddybuild logs. For getting the databinding library you might need to add `google()` to repositories under project `build.gradle` too.

2017-10-31 08:21 UTC, rakshakhegde approved these changes

2017-10-31 11:52 UTC, loicsiret commented
@rakshakhegde Yes, I'm trying to build on my bitrise account. But I will have issue. As soon it is solved, i will update my pr. Thank you

2017-10-31 15:29 UTC, rakshakhegde commented
FWIW, you don't need your own bitrise account. Buddybuild should show the logs to you too.

2017-11-01 04:04 UTC, merged